# Generated by Django 3.1 on 2024-12-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_black_friday_sale',
            field=models.BooleanField(default=False),
        ),
    ]
